#!/bin/bash
echo "Updating cloud-config"
bosh -n update-cloud-config <(curl -s 'https://raw.githubusercontent.com/cloudfoundry/cf-deployment/master/bosh-lite/cloud-config.yml')

echo ""
echo "Updating pipeline"
fly -t bucc set-pipeline -n -c ./pipelines/cf.yml -p cf \
    --var "bosh_target=${BOSH_ENVIRONMENT}" \
    --var "bosh_client=${BOSH_CLIENT}" \
    --var "bosh_client_secret=${BOSH_CLIENT_SECRET}" \
    --var "bosh_ca_cert=${BOSH_CA_CERT}"
